### ISSUE TITLE
Places without marker on the map

### ISSUE THREAD

**Issue by zuzust** [adab1ts/veinapp#43]
It seems that there are places from the search results that have no marker on the map.

See the snapshot below:
![veinapp](https://cloud.githubusercontent.com/assets/351530/23945554/36cfb274-0977-11e7-9f99-724343659e45.png)

**Comment by plastikaweb** [comment]
@zuzust There are 3 places in the search with the same location: 
`{"name":"AV CAMP D'EN GRASSOT","address":"AP. DE CORREUS 34090","zip":"08080","city":"Barcelona","latitude":"41.3879170","longitude":"2.1699187","telephone":"600 603 605","email":"avcampgrassot@telefonica.net","web":""}`
`{"name":"AV Raval","address":"Miquel Servet 211 (pla\u00e7a interior)","zip":"08912","city":"Badalona","latitude":"41.387917","longitude":"2.1699187","telephone":"933 972 516","email":"avvravalbdn@hotmail.com","web":"www.ravalbadalona.com"}`
`{"name":"AV Verneda Alta","address":"c\/ Campo Arriaza 99-101","zip":"08020","city":"Barcelona","latitude":"41.387917","longitude":"2.1699187","telephone":"93 314 58 13","email":"avvecinos@hotmail.com","web":null}`

If you pay attention, in the map there are 3 markers overlapped (the shadow is darker because of that)
